[package]
name = "unbase"
version = "0.0.2"
authors = ["Daniel Norman <daniel@gudtech.com>"]
description = "Unbase intends to be a causal, coordination-free distributed data-persistence and application framework. It is fundamentally reactive, fault tolerant, and decentralized."
documentation = "https://docs.rs/unbase/"
homepage = "https://unba.se"
repository = "https://github.com/unbase/unbase"
readme = "README.md"
categories = ["database"]
license = "Apache-2.0"
#build = "build.rs"
exclude = [
    "docs/*",
    "jekyll-docs-template/*",
    "old/*",
    "simulation/*",
    "schema/*"
]

[dependencies]
futures = "0.1.17"
linked-hash-map = "0.3.0"
sha2 = "0.4.0"
itertools = "0.5.9"
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
nihdb = "0.3.0"
tokio = "0.1.1"

[features]
single_threaded = []
#[build-dependencies]
#capnpc = "0.8"
